In [2]:
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [3]:
import tensorflow as tf
# keras use tensorflow to make neural networks
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
df = pd.DataFrame({
  "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
    0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
  "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
    35, 24, 33, 33, 21, 25, 20, 29],
  "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
    12, 5, 9, 11, 2, 6, 1, 9],
  "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [7]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water']]
y = df['needs_water']

In [8]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [9]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours  needs_water
0        0.066667         0.9375        0.727273          1.0
1        0.133333         0.6875        0.636364          1.0
2        0.200000         0.4375        0.545455          1.0
3        0.266667         0.1875        0.272727          0.0
4        0.466667         0.5625        0.636364          0.0
5        0.733333         0.6875        0.818182          0.0
6        0.400000         0.0000        0.181818          0.0
7        0.173333         0.1875        0.818182          1.0
8        0.533333         1.0000        1.000000          0.0
9        0.000000         0.3125        0.363636          1.0
10       1.000000         0.8750        0.727273          0.0
11       0.293333         0.8750        0.909091          1.0
12       0.666667         0.1250        0.090909          0.0
13       0.866667         0.3750        0.454545          0.0
14       0.093333         0.0625        0.000000          1.0
15       0.333333         0.6250        0.727273          1.0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, 
test_size=0.25, random_state=42, stratify = y)

In [11]:
# sequectial is used to create the layers
# Transforms a neuron's output and helps the network learn non-linear relationships.

model = keras.Sequential([
  layers.Input(shape = (X_train.shape[1], )),   # Input layer
  layers.Dense(8, activation='relu'),   # Hidden Layer

  # Output Layers...
  layers.Dense(1, activation= 'sigmoid'),  # Op layer (sigmoid => op will be in 0/1)

  # here we're using diff type of activation function

  # For categorical output (0 1 0, ......)
  # layers.Dense(3, activation= 'softmax')

  # For multi-level numerical output sparse_cross_entropy (1 2 3 4 5 ........)
  # layers.Dense(6, activation= 'sofmax')
])

In [ ]:
# optimizer => Algorithm that updates weights and biases to reduce loss.
# log loss => Measures the error between predicted output and actual output.
# metrics => based on which we evaluate the model

model.compile(optimizer='sgd', loss = 'binary_crossentropy', metrics=['accuracy'])

# here we're using different type of loss function 

# model.compile(optimizer='sgd', loss = 'categorical_crossentropy', metrics=['accuracy'])

# For Sparse_cross_entropy
# model.compile(optimizer='sgd', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# For optimizers... (SGD => Stocastic Gradient Descent)
model.compile(optimizer='opt', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
# One epoc => one forward, one backward

history = model.fit(
  X_train.values, y_train.values,   # training the model
  validation_data = (X_test.values, y_test.values),  # testing

  # 100 times forward and backward
  # batch_size = 4 (takes 4 rows and train) means 4 rows are passing together from input layer
  # verbose will say what is happening in training in each epochs like here 100
  # if verbose = 2 then 50 times it'ld have showed
  epochs = 100, batch_size = 4, verbose = 0
)

In [28]:
import tensorflow as tf

In [ ]:
opt = tf.keras.optimizers.SGD(learning_rate=0.01, momentum= 0.9)